### ISSUE TITLE
Paging feature doesn't respect browser navigation semantics.

### ISSUE THREAD

**Issue by p--b** [alown/eMonies#30]
I paged on purchase listing and was intensely disappointed when my browser's navigational controls no longer functioned.

Apologies if this is not in this repository's commits.

**Comment by alown** [comment]
Looks like smartlisting gem doesn't care much for this feature.
Uses Kaminara as its backend. This may be able to do so.

**Comment by alown** [comment]
Fixed as part of c0373acb768a3b71393896e6b3745ee99c1d2bef

(This may have removed sorting though, nobody needed that anyway)
