### ISSUE TITLE
Raise pagination

### ISSUE THREAD

**Issue by krazy00nothing** [alown/eMonies#40]
More things per page reduces pagination click-through (at the expense of increased scrolling, which is easier).

This would probably necessitate some form of break-up to prevent MONSTER TABLE occurring.

Current suggestions for break-ups:

- Number 'n' of transactions / Break / n transactions / break / etc
- Month a transactions / Break / Month b transactions / break / etc

Current chicken entries suggest monthly break-up would not result in overly large tables per month, only a month of move-in transactions comes close to a current 'normal' page's worth.

**Comment by alown** [comment]
I presume you either meant "raise pagination limit" or "raze pagination"?

Lets try switching to monthly first and see how slow it makes it...

**Comment by krazy00nothing** [comment]
Either works.

WOO MONTHLY
